apiVersion: v1
kind: Pod
metadata:
  namespace: demos
  name: configmaps-demo-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 3600; done
    volumeMounts:
    - name: my-config
      mountPath: /etc/config
  volumes:
  - name: my-config
    configMap:
      name: my-app-config
